# Generated by Django 2.1.2 on 2018-12-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billete', '0003_billete_git'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billete',
            old_name='git',
            new_name='gif',
        ),
    ]
