# Generated by Django 2.1.2 on 2018-12-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billete',
            name='url_imagen_reverso',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
