# Generated by Django 2.1.2 on 2018-12-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billete', '0002_billete_url_imagen_reverso'),
    ]

    operations = [
        migrations.AddField(
            model_name='billete',
            name='git',
            field=models.ImageField(default='default.gif', upload_to=''),
        ),
    ]
